Repository mdl29/scratchy, pull requests merged in 2021-07, with the labels that each got.

#229 227 missing key
  server/scratchy_server/model/messageModel.py
  server/scratchy_server/model/roomModel.py
  server/scratchy_server/model/userModel.py
  server/scratchy_server/test/global.yaml
  server/scratchy_server/test/test_AllRoom.tavern.yaml
  server/scratchy_server/test/test_room.tavern.yaml
  server/scratchy_server/test/test_user.tavern.yaml
Labels: 🔧 Backend

#230 179 update app component
  front/src/index.html
  front/src/js/activity_bar.js
  front/src/js/message-list.js
  front/src/js/room_list.js
  front/src/js/service.js
  front/src/js/user-list.js
  server/scratchy_server/__main__.py
  server/scratchy_server/resources/roomres.py
Labels: enhancement, 🚀 Frontend

#235 fixes #233 change button css and reorganize activity bar html
  front/src/css/activity_bar.css
  front/src/js/activity_bar.js
Labels: enhancement, 🚀 Frontend

#236 Fixes #226 implement cacheing on the service
  front/src/js/service.js
Labels: enhancement, 🚀 Frontend

#239 229 updated readme.md
  README.md
  doc/frontend/frontend.md
Labels: bug, documentation
