Repository mdl29/scratchy, pull requests merged in 2021-04, with the labels that each got.

#60 59 fix database import
  server/scratchy_server/resources/messageres.py
  server/scratchy_server/resources/userres.py
Labels: bug

#67 22 better readme server
  server/README.md
Labels: documentation

#63 #56 add clean logger
  server/README.md
  server/scratchy_server/app.py
  server/scratchy_server/resources/messageres.py
  server/scratchy_server/resources/roomres.py
  server/scratchy_server/resources/userres.py
Labels: enhancement, 🔧 Backend

#73 [Doc] Fixes #72 : UML Class diagram for front App
  doc/front-uml-class-diagram.dia
  doc/front-uml-class-diagram.png
Labels: documentation, enhancement

#64 📝 update front documentation
  doc/backend/model.png
  doc/frontend/front.png
  doc/frontend/frontend.md
Labels: documentation

#61 resolves #58 create user-list
  front/room.html
  front/user-list.html
Labels: enhancement, 🚀 Frontend

#83 added put command, closed #79
  server/README.md
  server/scratchy_server/resources/messageres.py
  server/scratchy_server/resources/roomres.py
  server/scratchy_server/resources/userres.py
Labels: enhancement

#82 Fixes #80 : fixes mistakes in uml diagram
  doc/front-uml-class-diagram.dia
  doc/front-uml-class-diagram.png
Labels: bug, 🚀 Frontend

#85 fixed #81 by adding 1 char incredible !!!
  server/scratchy_server/model/roomModel.py
Labels: bug, 🔧 Backend

#86 Fixes #75 create the login component according to the specs i added on the issue
  front/css/login.css
  front/login.html
Labels: 🚀 Frontend

#84 Resolves #22 [Doc] Better read me
  README.md
  doc/backend/API-documentation.md
  doc/frontend/frontend.md
  server/README.md
Labels: documentation

#95 Resolves #87 [Front] refractor text_editor
  front/message_editor.html
Labels: enhancement, 🚀 Frontend

#100 Fixes #87 delete old text_editor, change css class names an move to files
  front/css/global.css
  front/css/message_editor.css
  front/message_editor.html
  front/text_editor.html
Labels: enhancement, 🚀 Frontend

#97 added linter doc, fixed #89
  README.md
  doc/tools/flake8.md
  logos/js.png
  logos/python.png
  logos/vue-js.jpg
  server/README.md
Labels: documentation, 🔧 Backend

#99 Resolves #92 [Doc] Add bagdes in README.md
  README.md
Labels: documentation, enhancement

#106 Fixes #105 added missing css
  front/css/global.css
  front/css/room.css
  front/css/user-list.css
  front/room.html
  front/user-list.html
Labels: 🚀 Frontend

#111 Fixes #107 added activity bar
  front/activity_bar.html
  front/css/activity_bar.css
Labels: enhancement, 🚀 Frontend

#112 Fixes #108 add room editor
  front/css/room_editor.css
  front/room_editor.html
Labels: enhancement, 🚀 Frontend

#115 Resolves #114 [Doc] add links to frontend files
  doc/frontend/frontend.md
  front/css/messages-list.css
  front/messages-list.html
  logos/html.png
Labels: documentation, duplicate, 🚀 Frontend

#122 Resolves #121 Cleaner file organisation
  README.md
  front/.gitignore
  front/frontend.md
  front/src/activity_bar.html
  front/src/css/activity_bar.css
  front/src/css/global.css
  front/src/css/login.css
  front/src/css/message_editor.css
  front/src/css/messages-list.css
  front/src/css/room_editor.css
  front/src/css/room_list.css
  front/src/css/user-list.css
  front/src/login.html
  front/src/message_editor.html
  front/src/messages-list.html
  front/src/room_editor.html
  front/src/room_list.html
  front/src/user-list.html
Labels: documentation, enhancement, 🚀 Frontend
