Repository mdl29/scratchy, pull requests merged in 2021-05, with the labels that each got.

#116 Fixes #90 gather all components
  front/css/activity_bar.css
  front/css/app.css
  front/css/login.css
  front/css/messages-list.css
  front/css/room_editor.css
  front/css/user-list.css
  front/index.html
  front/js/activity_bar.js
  front/js/login.js
  front/js/message-list.js
  front/js/message_editor.js
  front/js/room_editor.js
  front/js/room_list.js
  front/js/user-list.js
Labels: 🚀 Frontend

#120 begin #96 open api
  server/README.md
  server/requirements.txt
  server/scratchy_server/app.py
  server/scratchy_server/model/messageModel.py
  server/scratchy_server/model/objectIdSchema.py
  server/scratchy_server/model/roomModel.py
  server/scratchy_server/model/userModel.py
  server/scratchy_server/resources/messageres.py
  server/scratchy_server/resources/roomres.py
  server/scratchy_server/resources/userres.py
Labels: documentation, 🔧 Backend

#153 resolves #133 : added profileImage attr in curl cmd under Update User
  server/README.md
Labels: documentation, enhancement

#163 fixes #121 cleaner file organisation
  front/.gitignore
  front/package-lock.json
  front/package.json
  front/src/activity_bar.html
  front/src/css/activity_bar.css
  front/src/css/app.css
  front/src/css/global.css
  front/src/css/login.css
  front/src/css/message_editor.css
  front/src/css/messages-list.css
  front/src/css/room_editor.css
  front/src/css/room_list.css
  front/src/css/user-list.css
  front/src/index.html
  front/src/js/activity_bar.js
  front/src/js/login.js
  front/src/js/message-list.js
  front/src/js/message_editor.js
  front/src/js/room_editor.js
  front/src/js/room_list.js
  front/src/js/user-list.js
  front/src/login.html
  front/src/message_editor.html
  front/src/messages-list.html
  front/src/room_editor.html
  front/src/room_list.html
  front/src/user-list.html
Labels: enhancement

#141 resolved #131 : added CONTRIBUTING.md
  CONTRIBUTING.md
  doc/example_issue.png
Labels: documentation

#164 #103 css linter
  doc/tools/stylelint.md
  front/.stylelintrc.json
  front/src/css/activity_bar.css
  front/src/css/app.css
  front/src/css/global.css
  front/src/css/login.css
  front/src/css/message_editor.css
  front/src/css/messages-list.css
  front/src/css/room_editor.css
  front/src/css/room_list.css
  front/src/css/user-list.css
Labels: enhancement

#180 Resolves #174 upgrade postcss
  front/package-lock.json
  front/package.json
Labels: dependency, 🚀 Frontend

#188 176 delete method returns empty json structure
  server/scratchy_server/resources/messageres.py
  server/scratchy_server/resources/roomres.py
  server/scratchy_server/resources/userres.py
  server/scratchy_server/test/test_message.tavern.yaml
  server/scratchy_server/test/test_room.tavern.yaml
  server/scratchy_server/test/test_user.tavern.yaml
Labels: documentation, 🔧 Backend

#184 Resolves #181 : Make a better CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
  doc/example/example-description.png
  doc/example/example-issue.png
  doc/example/example-pr.png
  doc/example/example_pr_title.png
  doc/example_issue.png
Labels: documentation, enhancement

#193 Fixes #192 : Edit scratchy service to take advantage of the new api endpoints
  front/src/js/service.js
Labels: enhancement, 🚀 Frontend

#195 Fixes #158 : Get messages by roomId #187
  server/README.md
  server/scratchy_server/model/messageModel.py
  server/scratchy_server/model/objectIdSchema.py
  server/scratchy_server/resources/messageres.py
  server/scratchy_server/test/test_AllMessage.tavern.yaml
Labels: bug, enhancement, 🔧 Backend

#196 Fixes #172 : Add handling of mongoengine.errors.validation error #173
  server/scratchy_server/filters/mongoexception.py
  server/scratchy_server/resources/messageres.py
  server/scratchy_server/resources/roomres.py
  server/scratchy_server/resources/userres.py
  server/scratchy_server/test/global.yaml
  server/scratchy_server/test/test_room.tavern.yaml
Labels: bug, enhancement, 🔧 Backend

#197 Resolves #140 : Refresh timestamp in message-list.js file
  front/src/js/message-list.js
Labels: enhancement, 🚀 Frontend

#199 Fixes #198 : Add a summary in README.md
  README.md
Labels: documentation, enhancement

#201 200 Fix mistake
  server/scratchy_server/resources/messageres.py
  server/scratchy_server/resources/userres.py
Labels: bug, urgent, 🔧 Backend

#203 Fixes #202 : Add usersID param in updateRoom function
  front/src/js/service.js
Labels: documentation, 🚀 Frontend
