Repository mdl29/scratchy, pull requests merged in 2021-06, with the labels that each got.

#207 189 improve swagger
  server/scratchy_server/app.py
  server/scratchy_server/model/messageModel.py
  server/scratchy_server/model/roomModel.py
  server/scratchy_server/model/userModel.py
  server/scratchy_server/resources/messageres.py
  server/scratchy_server/resources/roomres.py
  server/scratchy_server/resources/userres.py
  server/scratchy_server/test/global.yaml
  server/scratchy_server/test/test_AllMessage.tavern.yaml
  server/scratchy_server/test/test_message.tavern.yaml
  server/scratchy_server/test/test_room.tavern.yaml
  server/scratchy_server/test/test_user.tavern.yaml
Labels: enhancement, 🔧 Backend

#206 Fixes #139 : UI display the room id to share it
  front/src/css/activity_bar.css
  front/src/icons/share-icon-black.svg
  front/src/icons/share-icon-white.svg
  front/src/js/activity_bar.js
Labels: enhancement, 🚀 Frontend

#205 204 better contributing.md
  CONTRIBUTING.md
  doc/example/example-issue.png
  doc/example/example-pr.png
Labels: documentation

#210 191 add delete all method
  server/README.md
  server/scratchy_server/resources/messageres.py
  server/scratchy_server/resources/roomres.py
  server/scratchy_server/resources/userres.py
  server/scratchy_server/test/test_AllMessage.tavern.yaml
  server/scratchy_server/test/test_AllRoom.tavern.yaml
Labels: bug, 🔧 Backend

#213 190 Added test hook before every test
  server/scratchy_server/test/test.py
  server/scratchy_server/test/test_deleteAll.tavern.yaml
Labels: test, 🔧 Backend

#214 212 add search of rooms containing specific user
  server/scratchy_server/model/roomModel.py
  server/scratchy_server/resources/roomres.py
  server/scratchy_server/test/global.yaml
  server/scratchy_server/test/test_AllRoom.tavern.yaml
Labels: 🔧 Backend

#216 218 Add mongo exception validation in resources
  server/scratchy_server/resources/messageres.py
  server/scratchy_server/resources/roomres.py
  server/scratchy_server/resources/userres.py
Labels: enhancement, 🔧 Backend

#217 134 fixing schema
  server/scratchy_server/model/messageModel.py
  server/scratchy_server/model/objectIdSchema.py
  server/scratchy_server/model/roomModel.py
  server/scratchy_server/model/userModel.py
  server/scratchy_server/test/global.yaml
  server/scratchy_server/test/test_AllMessage.tavern.yaml
  server/scratchy_server/test/test_AllRoom.tavern.yaml
  server/scratchy_server/test/test_message.tavern.yaml
  server/scratchy_server/test/test_room.tavern.yaml
  server/scratchy_server/test/test_user.tavern.yaml
Labels: dependency, 🔧 Backend

#225 224 small improve with test
  server/scratchy_server/test/test.py
Labels: 🔧 Backend
