Repository mdl29/scratchy, pull requests merged in 2022-02, with the labels that each got.

#260 Fixes #259 : Replace V1 shield by the V2
  README.md
Labels: documentation

#258 Fixes #254 up to date the readme
  server/README.md
Labels: documentation, 🔧 Backend

#256 113 vuecli
  doc/frontend/front.png
  doc/frontend/frontend.md
  front/.browserslistrc
  front/.eslintrc.js
  front/.gitignore
  front/.stylelintrc.json
  front/README.md
  front/babel.config.js
  front/package-lock.json
  front/package.json
  front/public/favicon.ico
  front/public/favicon.svg
  front/public/index.html
  front/src/App.vue
  front/src/assets/share-icon-black.svg
  front/src/assets/share-icon-white.svg
  front/src/components/ActivityBar.vue
  front/src/components/Login.vue
  front/src/components/MessageEditor.vue
  front/src/components/MessageList.vue
  front/src/components/RoomEditor.vue
  front/src/components/RoomList.vue
  front/src/components/UserList.vue
  front/src/css/app.css
  front/src/css/global.css
  front/src/css/messages-list.css
  front/src/css/room_editor.css
  front/src/index.html
  front/src/js/activity_bar.js
  front/src/js/login.js
  front/src/js/message-list.js
  front/src/js/message_editor.js
  front/src/js/room_editor.js
  front/src/js/room_list.js
  front/src/js/user-list.js
  front/src/main.ts
  front/src/service.ts
  front/src/shims-vue.d.ts
  front/tsconfig.json
Labels: enhancement, 🚀 Frontend

#261 [Front] Add a button for copy to clipboard the current room id
  front/src/components/ActivityBar.vue
Labels: enhancement, 🚀 Frontend
